### ISSUE TITLE
Squiggly error line persists after error is corrected

### ISSUE THREAD

**Issue by R-Bower** [tktonjy/customizable_editor_tabs#1]
@tktonjy When there's an error in an open file, the squiggly line will persist even after the error is corrected.

![image](https://user-images.githubusercontent.com/11933208/151617215-c111c6fd-7b48-4224-9511-80780a389d91.png)

**Comment by tktonjy** [comment]
fixed in 1.12. Please check and reopen if any issues

**Comment by R-Bower** [comment]
Confirmed working, thanks!
